version: '3'

services:
  db:
    image: mariadb:11.1.3
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vsp}
      MYSQL_USER: ${MYSQL_USER:-vsp}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-vsp}
    ports:
      - "3306:3306"
  web:
    restart: always
    depends_on:
      - db
    volumes:
      # - /path/to/your/games.log:/vsp/games.log
      # - /path/to/your/server.gif:/vsp/pub/images/server.gif
      # - /path/to/your/logo.gif:/vsp/pub/images/logo.gif
      - logdata:/vsp/logdata
    ports:
      - 80:80
    environment:
      TZ: Europe/Berlin
      # needs to be at least 6 characters long
      # VSP_WEB_PASSWORD:
      DB_NAME: vsp
      # use the same value as for MYSQL_USER
      DB_USERNAME: ${MYSQL_USER:-vsp}
      # use the same value as for MYSQL_PASSWORD
      DB_PASSWORD: ${MYSQL_PASSWORD:-vsp}
volumes:
  logdata:
