version: '3'

services:
  db:
      environment:
        MYSQL_DATABASE: ${VSP_DB_NAME}
        MYSQL_USER: ${VSP_DB_USERNAME}
        MYSQL_PASSWORD: ${VSP_DB_PASSWORD}
  web:
    build: .
    # ports:
      # supervisor web gui would be available on port 9001
      # - 9001:9001
    volumes:
      - ./osp.log:/vsp/games.log
    environment:
      DB_NAME: ${VSP_DB_NAME}
      DB_USERNAME: ${VSP_DB_USERNAME}
      DB_PASSWORD: ${VSP_DB_PASSWORD}
